name: Ubuntu SSH to GitHub Actions

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # * install/setup extra tools
      - name: Install `deno` toolchain
        uses: denoland/setup-deno@v1
      # *
      - name: SSH Keepalive Hack
        run: |
          mkdir -p ~/.ssh
          cat << EOF > ~/.ssh/config
          Host *
              ServerAliveInterval 60
              StrictHostKeyChecking no
          Host github.com
              User git
              Port 22
              Hostname github.com
              TCPKeepAlive yes
              IdentitiesOnly yes
          EOF
      # - name: Start SSH via ngrok
      #   continue-on-error: true
      #   timeout-minutes: 350
      #   uses: ./.github/actions/ssh2actions
      #   with:
      #     mode: ngrok
      #   env:
      #     NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      #     NGROK_REGION: us
      #     SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - name: Start SSH via tmate
        continue-on-error: true
        timeout-minutes: 350
        uses: ./.github/actions/ssh2actions
        with:
          mode: tmate
        # env:
        #   NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        #   NGROK_REGION: us
        #   SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        #   TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        #   TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
